# Alternative app.yaml for POLLING mode
# Use this if webhooks don't work due to authentication issues

command:
  - "python"
  - "main_polling.py"

env:
  - name: TELEGRAM_BOT_TOKEN
    value: "<YOUR TELEGRAM TOKEN)"
  - name: DATABRICKS_SERVING_ENDPOINT
    value: "<YOUR SERVICE ENDPOINT>"
  - name: POLL_INTERVAL
    value: "2"  # Poll every 2 seconds

