# Alternative app.yaml for POLLING mode
# Use this if webhooks don't work due to authentication issues

command:
  - "python"
  - "main.py"

env:
  - name: TELEGRAM_BOT_TOKEN
    value: "<Your Telegram Bot Token>"
  - name: DATABRICKS_SERVING_ENDPOINT
    value: "Your Databricks Serving Endpoint"
  - name: POLL_INTERVAL
    value: "2"  # Poll every 2 seconds

